prepare:
  fetch:
    - https://raw.githubusercontent.com/bkuhlmann/code_quality/v0.3.0/configurations/.rubocop.yml
engines:
  shellcheck:
    enabled: true
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
ratings:
  paths:
  - "app/**/*"
  - "bin/**/*"
  - "lib/**/*"
  - "**.rb"
  - "**.js"
exclude_paths:
- "spec/**/*"
- "vendor/**/*"
- ".codeclimate.yml"
